version: '3'
services:
    postgres-db:
        image: "postgres"
        environment:
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api

    blog-api:
        image: garg882/simple-blog-api
        build: .
        ports:
            - "3000:3000"
        environment:
            - POSTGRES_HOST=postgres-db
            - POSTGRES_PORT=5432
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api

